/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jogodogenio;

import java.awt.Font;

/**
 *
 * @author nonak
 */
public class TelaJogo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJogo.class.getName());

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        String texto = ( "<html> Estou pensando em um número entre 0 e 5. Tente adivinhar que valor é esse.</html");
        lblBalao.setText(texto);
        
        lblClick.setVisible(false);
        lblReceba.setVisible(false);
        btnPrem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPalp = new javax.swing.JButton();
        txtNum = new javax.swing.JSpinner();
        lblBalao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnPrem = new javax.swing.JButton();
        lblReceba = new javax.swing.JLabel();
        lblClick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPalp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnPalp.setText("Palpite");
        btnPalp.addActionListener(this::btnPalpActionPerformed);
        getContentPane().add(btnPalp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 110, -1));

        txtNum.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        getContentPane().add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 60, -1));

        lblBalao.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBalao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalao.setText("Frase");
        lblBalao.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblBalao.setAutoscrolls(true);
        lblBalao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblBalao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblBalao.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 220, 90));

        jLabel2.setText("VALOR");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nonak\\OneDrive\\Documentos\\NetBeansProjects\\JogoDoGenio\\nbproject\\imagem\\genio.jpg")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 374, 516));

        btnPrem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrem.setText("Clique!!!");
        btnPrem.addActionListener(this::btnPremActionPerformed);
        getContentPane().add(btnPrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        lblReceba.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lblReceba.setText("Seu premio é estudar mais.");
        getContentPane().add(lblReceba, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 90, 130, 50));

        lblClick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClick.setText("Clique e pegue seu premio.");
        lblClick.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 170, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpActionPerformed
        // TODO add your handling code here:
        int resp = (int) (Math.random() * 6); //int resp = (int) ((int) 0+Math.random() * (6-0)); FUNCIONA, MAS ESTÁ ERRADO
        int num = Integer.parseInt(txtNum.getValue().toString());
        String r1 = "ACERTOU!!!";
        String r2 = "<html>ERROU! Pensei em " + resp + ".</html>";      
        String resul = (resp == num)? r1 : r2; //NÃO ESTAVA COLOCANDO O STRING E DAVA ERRO
        
        lblBalao.setFont(new Font("Arial Black", Font.PLAIN, 22));
        
        lblBalao.setText(resul);
        
        if (resul == r1){
            lblClick.setVisible(true);
            btnPrem.setVisible(true);
        }
        
       
        
    }//GEN-LAST:event_btnPalpActionPerformed

    private void btnPremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremActionPerformed
        // TODO add your handling code here:
        lblReceba.setVisible(true);
        lblReceba.setText("<html>Seu prêmio é<br>estudar mais.</html>");

    }//GEN-LAST:event_btnPremActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJogo().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalp;
    private javax.swing.JButton btnPrem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblClick;
    private javax.swing.JLabel lblReceba;
    private javax.swing.JSpinner txtNum;
    // End of variables declaration//GEN-END:variables
}
